[package]
name = "noise"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.50"
noise = "0.6.0"
perlin_noise = "1.0.1"
lazy_static = "1.4.0"

[profile.dev]
lto = true
opt-level = 3

[profile.release]
lto = true
opt-level = 3

